server:
  port: 8082

spring:  datasource:    url: jdbc:mysql://localhost:3306/AuthService?createDatabaseIfNotExist=true&useSSL=false 
    username: root
    password: 15214324
  jpa:#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect        '[format_sql]': true
    hibernate:      ddl-auto: update
        
      
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
#server.port=8082
#spring.datasource.url=jdbc:mysql://localhost:3306/AuthService?createDatabaseIfNotExist=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=Jee@1234
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.format_sql=true 